#pragma once
#define ECCS_SDK_VERSION_MAJOR 1
#define ECCS_SDK_VERSION_MINOR 0
#define ECCS_SDK_VERSION_PATCH 0
// 字符串形式，用于打印和返回
#define ECCS_VER_STR "1.0.0"

// 内部校验用的整数版本 (例如 10000)
#define ECCS_VER_NUM (ECCS_SDK_VERSION_MAJOR * 10000 + ECCS_SDK_VERSION_MINOR * 100 + ECCS_SDK_VERSION_PATCH)